### ISSUE TITLE
DummyDisplay missing - didn't make it when the repo changed[BUG]

### ISSUE THREAD

**Issue by Sniffleupagus** [jayofelony/pwnagotchi#108]
**Describe the bug**

DummyDisplay appeared around 2.8.2, but is missing from recent versions.

**To Reproduce**
Check out new version and see that it isn't there.

In the commit where you switched repos, maybe from -bookworm back to just pwnagotchi, lots (all?) of files were removed, including the ones with DummyDisplay. New files are added back in, but they do not have DummyDisplay (which was included right before that commit).

Any way to bring it over?

**Comment by jayofelony** [comment]
Sure, ill look into it
