### ISSUE TITLE
[BUG] Pwnagotchi doesn't boot anymore

### ISSUE THREAD

**Issue by julien-stiker** [jayofelony/pwnagotchi#112]
Hello,

since this night my pwnagotchi doesn't boot anymore... I think, he downloaded the last release 2.8.9 this night...

The screen blink... The connection doesn't establish if I use micro-usb...

My config : 
Piz 2 WH
Waveshare 4
PiSugar 3

**Comment by Salam9000** [comment]
Same here, 
Piz WH
Waveshare 4
PiSugar S

**Comment by wpa-2** [comment]
> Hello,
> 
> since this night my pwnagotchi doesn't boot anymore... I think, he downloaded the last release 2.8.9 this night...
> 
> The screen blink... The connection doesn't establish if I use micro-usb...
> 
> My config : Piz 2 WH Waveshare 4 PiSugar 3



> Same here, Piz WH Waveshare 4 PiSugar S

`sudo pwnagotchi --debug`

**Comment by rsun0525** [comment]
This is related to the bug I filed, where my manual change to uncomment disable-wifi was overwritten, after I modified it again to remove the comment, everything started working.
