### ISSUE TITLE
[BUG] RPI02W Waveshare v3 screen not updating

### ISSUE THREAD

**Issue by abonforti** [jayofelony/pwnagotchi#115]
**Describe the bug**
Screen is frozen, however accessing via http://10.0.0.2:8080 it shows changes

**To Reproduce**

1. Flash the latest version
2. Connect the Waveshare v3

**Expected behavior**
Screen should auto update

**Environment (please complete the following information):**
 - Pwnagotchi version 2.8.9 64bit
 - Type of hardware RPI02W

**Additional context**
pwnagotchi --debug output can be found here: https://nopaste.net/W8amOjrQJN
config.toml can be found here: https://nopaste.net/LOvnPsxRYo

**Comment by jayofelony** [comment]
main.plugins.bt-tether.devices.ale-iPhone13.enabled

You cannot rename it to ale-iPhone, keep it ios.

**Comment by abonforti** [comment]
I have replaced that, and noticed some more stability within the network, but the issue on the screen persists.

**Comment by abonforti** [comment]
But that is strange because with a pizero w and the 32bit image, I had no problem…

**Comment by abonforti** [comment]
My bad, that was just a typo, I’ve corrected this and confirm I am using a v3 screen.

**Comment by jayofelony** [comment]
Ok you can access the webui over usb or through bt tether? And it worked on a pi0w,so that means you have bad soldering on the gpio pins. Because the software has no issues with e-ink displays.

**Comment by abonforti** [comment]
Just to be on the safer side, I've re-soldered all the pins. But it's strange because as soon as I start the pwnagotchi daemon, the screen works and updates (I can see the little pipe character blinking), then it kind of freezes...
