### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rsun0525** [jayofelony/pwnagotchi#119]
**Describe the bug**
I modify /boot/firmware/config.txt to remove the comment of dtoverlay=disable-wifi under [all]

but sometime later, I notice it's commented again, almost like this file is getting overwritten by some default, is there a more proper way to enable disable-wifi in your config?  I wasn't expecting to change itself.

**Comment by jayofelony** [comment]
It get overwritten with every auto update

**Comment by rsun0525** [comment]
yes, I would think once it's set, shouldn't touch it in an autoupdate, but from now on I know to check it.

**Comment by jayofelony** [comment]
RPi tends to change stuffso I might need to change stuff in it to keep stuff working and to avoid unnecessary reflashing.
