### ISSUE TITLE
[BUG] the UPS-litev1.3 plugin sometimes does not "start"

### ISSUE THREAD

**Issue by formula-spectre** [jayofelony/pwnagotchi#130]
**Describe the bug**
basically I have the UPSLitev1.3 plugin enabled; and sometimes it works and sometimes not; but I recently that of recently it does not work; it shows if the UPS is plugged in or not, but not the battery percentage; but if I simply ssh into my pwnagotchi, then `python UPS_Lite_V1.3_CW2015.py`, it displays both on the script output and the plugin (the top bar to be more clear) the battery percentage.
I think this might relate to the fact that sometimes the rpi reboots multiple times if an external antenna is inserted? as of now I noticed that it boots, stays alive some seconds, reboots, then proceeds like normal, aside from the plugin.  
the mentioned python script can be (found here)[https://github.com/linshuqin329/UPS-Lite/blob/master/UPS-Lite_V1.3_CW2015/UPS_Lite_V1.3_CW2015.py]

**To Reproduce**
1. have an UPSLite (the vendor said that they only produce 1.3 now)
2. use the UPSLitev1.3 plugin
3. ???
4. see the battery value not appearing
5. ???

**Expected behavior**  
I expect that I get the battery %, maybe not as soon as it boots, but at least some seconds after

**Screenshots**
I can post a video of the whole ordeal if it can help

**Environment (please complete the following information):**
 - Pwnagotchi version: 2.8.9
 - OS Version: Debian 12 on the rpi
 -  raspberry pi02W
 - UPSLite V1.3, microusb to full size usb angled adapter, CUDY AC650 mini antenna 

**Additional context**
it used to work like magic before some updates, but as of recently I recently this. it's not a big deal, i can `ssh pwnagotchi -t python ~/script.py` through termux, but i'd prefer that I get the battery % automatically. the multiple reboot seem to be not happening anymore, so I don't think that is another issue I need to file, but if it will happen again I will

**Comment by rai68** [comment]
Is i2c enabled? if you have python errors it may be better to contact the plugin author
