### ISSUE TITLE
support for the orange pi zero 2W?

### ISSUE THREAD

**Issue by formula-spectre** [jayofelony/pwnagotchi#136]
as I mentioned  in https://github.com/aluminum-ice/pwnagotchi/issues/122 basically it would be a good step up to have the orange pi zero 2W supported; it has a built in 2.4/5GHz antenna, and two usb C instead of micro-b; I tried the same setup described in the issue for this fork of pwnagotchi, but still it does not boot,  nor `usb0` appears; any ideas on why? it should be compatible, since the AllWinner H618 is a ARMv8. and 64 bits; Yet it does not; am I missing something?

**Comment by jayofelony** [comment]
Doesnt support monitor mode on the built-in wifi.
