### ISSUE TITLE
[BUG] Incorrect use of assignment operator (=) instead of comparison operator (==) in draw method of ui/components.py

### ISSUE THREAD

**Issue by kszabi1** [jayofelony/pwnagotchi#137]
**Describe the bug**
The draw method in the ui/components.py file incorrectly uses the assignment operator (=) instead of the comparison operator (==) in an if statement. This causes the self.image to be inverted unconditionally, which is not the intended behavior.

**To Reproduce**
Basically when the pwnagotchi tries to auto start it fails and when I try to start with `sudo systemctl status pwnagotchi.service` it displays the error message. 

**Expected behavior**
The draw method should only invert the self.image when self.color is equal to 0xFF.

**Environment (please complete the following information):**
 - Pwnagotchi version: v2.9.0
 - OS version:  Raspbian GNU/Linux version 11
 - Type of hardware: RPi0W 
 - Any additional hardware used: waveshare_4

**Comment by jayofelony** [comment]
Merged and building new image
