### ISSUE TITLE
pwnagotchi boots multiple times

### ISSUE THREAD

**Issue by sosdos** [jayofelony/pwnagotchi#143]
whenever I boot the pwnagotchi (using 2.8.9), it takes about 3-5 minutes to boot, and during that process it boots 2-3 times. how do i fix that and get it to boot once, as normal?

i can't update it since bt tether and the connection share script doesn't work. any solutions to that, too?

sorry if these are simple issues, I'm kind of new to this kind of stuff and can't find much online.

**Comment by sakkarose** [comment]
Can you provide errors and logs about your bt tether and connection share script problems.
Don't mind being new, just keep things detailed so ppl can help u.

**Comment by jayofelony** [comment]
No further details provided, closing. Open a new issue if still have issues.
