### ISSUE TITLE
Screen get wiped when shutting Down

### ISSUE THREAD

**Issue by JAKAMI99** [jayofelony/pwnagotchi#151]
**Describe the bug**
Screen gets wiped when shutting down.
The "Good Night" message works, but afterwards the screen seems to get cleared by some kind of function.

**Expected behavior**
The "Good Night - ZzZzZ" message appears and stays instead of a plain white screen.
**Screenshots**

**Environment (please complete the following information):**
 - Pwnagotchi version
 - OS version 2.9.1
 - Type of hardware Zero 2

**Comment by JAKAMI99** [comment]
The ui.invert option does not change the behavior. 
The Screen is always white, really weird.

**Comment by JAKAMI99** [comment]
I checked a few things, but no luck.
It happens no matter what I do. I tried to shut down the pwnagotchi with the web interface over my computer and also with my phone over Bluetooth tethering. 
It always does a screen clear by flickering a few times after the "Zzz" face is shown for about 6 seconds.

**Comment by jayofelony** [comment]
personality.clear_on_exit = true # clear display when shutting down cleanly

**Comment by JAKAMI99** [comment]
Thanks!
 But why would you implement it, is there a reason and why is it enabled by default?
