### ISSUE TITLE
Screen flashes but nothing happens after 

### ISSUE THREAD

**Issue by P3trol** [jayofelony/pwnagotchi#154]
**Describe the bug**
Just followed the install wizard, one the device had completed, the screen just flashes and nothing happens afterwords

**To Reproduce**
1. ...
2. ...
3. ...
Followed the setup wizard 

**Expected behavior**
Screen should show 

**Screenshots**

**Environment (please complete the following information):**
 - 2.89
 - raspberry pi zero w
 - waveshare v4 hat (250x122, 2.13inch E-Ink display HAT for Raspberry Pi	 product number:12915)

**Additional context**
I don't have a battery connected just my laptop's USB port

**Comment by jayofelony** [comment]
You sure its the v4, and not a G version?

**Comment by jayofelony** [comment]
No further details provided, closing.
