### ISSUE TITLE
[BUG] fixing "GPIO busy"

### ISSUE THREAD

**Issue by iandouglas** [jayofelony/pwnagotchi#158]
**Describe the bug**
The gpio_buttons plugin fails with some hardware because of the kernel changes with GPIO recently.

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**
I mentioned it in the discord community here: 
https://discord.com/channels/717817147853766687/717818155061346427/1241236096659099669

**Environment (please complete the following information):**
 - Pwnagotchi version: 2.8.9
 - Type of hardware: RPi Zero 2W, Waveshare 2.7inch e-Paper with 4 buttons

**Additional context**

```bash
sudo apt remove python3-rpi.gpio
sudo apt update
sudo apt install python3-rpi-lgpio
```

No other code changes were needed, and I can use the displays 4 buttons as GPIO 5, 6, 13 and 19 with the gpio-buttons plugin. This is purely a drop-in replacement package. Both `rpi.gpio` and `rpi-lgpio` import as the same module name, so while you can probably have both installed, it'll confuse your environment as to which module code to use.

**Comment by letsgo245** [comment]
nice

**Comment by jayofelony** [comment]
This is a nice update! I am testing this a we speak with a waveshare v2

**Comment by jayofelony** [comment]
Working and implemented.
