### ISSUE TITLE
Wouldn't it be cool if we could disable the cursor?

### ISSUE THREAD

**Issue by Sniffleupagus** [jayofelony/pwnagotchi#168]
Several people have asked about disabling the cursor this week

I propose a config variable to enable or disable it.  "ui.showcursor"

**Describe alternatives you've considered**
ui.nocursor, but the double negative seems silly.

**Additional context**
Tested on a pwny, then copy/pasted the change on GitHub.com

**Comment by RasTacsko** [comment]
I usually set the cursor to a _ character, because the blocky one moves the name tag by one pixel every time.
What if we can set the cursor character in config like in the fancygotchi themes?

**Comment by rai68** [comment]
implemented with #167 will be in next image
