### ISSUE TITLE
Pwangotchi says connected when my phone is not

### ISSUE THREAD

**Issue by MimoAW** [jayofelony/pwnagotchi#174]
I have an Google pixel 7 Pro I always used to be able to view the web UI through Bluetooth on my phone but one day it just stopped working the pwangotchi says connected but my phone is not connected. I have tried unpairing and untrusting and then repairing and trusting but it's still not working. It will also sometimes say be but then it'll just go back to connected.
Could I please have some help

**Comment by wpa-2** [comment]
Follow this 
https://pwnagotchi.org/common-issues/index.html#instructions

**Comment by MimoAW** [comment]
I have followed that guide previously. It did not solve my issue

**Comment by wpa-2** [comment]
> I have followed that guide previously. It did not solve my issue

The guide works perfectly so there's a good chance you have messed something up, have you made sure tethering is enabled.

**Comment by MimoAW** [comment]
Yes, Bluetooth tethering is enabled in hotspot. It was working perfectly fine but the next time I powered it on no changes to my phone or pwangotchi he just wouldn't connect and I did follow the guide multiple times

**Comment by MimoAW** [comment]
I have fixed it. I stupidly had Android phone Bluetooth tether set to false 🤦 thanks for your help
