### ISSUE TITLE
Problem on the display

### ISSUE THREAD

**Issue by coutud** [jayofelony/pwnagotchi#175]
Hello i have a problem on the display The battery level that is displayed overlaps with the bt connection indication how i can separe them

Thanks

**Comment by jayofelony** [comment]
Either use tweakview plugin or edit the corresponding plugin you wish to edit the location of.

**Comment by coutud** [comment]
HelloOk but i don’t know how to do itThanks Envoyé de mon iPhoneLe 25 juin 2024 à 19:27, Jayofelony ***@***.***> a écrit :﻿
Either use tweakview plugin or edit the corresponding plugin you wish to edit the location of.

**Comment by renewedbullet** [comment]
https://pwnagotchi.org/customization/tweak-view/index.html

Tweak view is a plugin for pwnagotchi that allows you to move UI elements.

**Comment by rai68** [comment]
> https://pwnagotchi.org/customization/tweak-view/index.html
> 
> Tweak view is a plugin for pwnagotchi that allows you to move UI elements.

Closing, fix is above
