### ISSUE TITLE
disk image file corrupted  ? 

### ISSUE THREAD

**Issue by PWORLDMOB** [jayofelony/pwnagotchi#176]
keep getting disk image file corrupted .

**Comment by renewedbullet** [comment]
What imaging program are you using?

**Comment by PWORLDMOB** [comment]
7zip and balena etcher . Seems to work for the aluminum ice image but I really like this one .

**Comment by renewedbullet** [comment]
Do not extract it and use rpi imager galena doesn’t expand the file system properly.

**Comment by PWORLDMOB** [comment]
Thanks mate ! RpI imag worked like a charm
