### ISSUE TITLE
[BUG] Waveshare Lcdhat 240x240 dont work

### ISSUE THREAD

**Issue by ViniSug** [jayofelony/pwnagotchi#178]
**Describe the bug**
Waveshare Lcdhat 240x240 dont work on jayofelony 2.8.9 version.
I tried aluminum-ice 1.8.5 and works fine on same hardware, using same configuration.

**To Reproduce**
1. Set config: ui.display.type = "lcdhat"
2. Reboot
3. Display dont show anything, but webui works fine.

**Environment:**
 - Pwnagotchi version 2.8.9
 - Type of hardware: RaspiberryPi Zero 2W

**Comment by jayofelony** [comment]
Edit `/boot/firmware/config.txt` to match `dtoverlay=spi0-2cs`, I think that should work.

**Comment by rai68** [comment]
Please comment if working. will close within 3days after
