### ISSUE TITLE
[BUG]Pi zero 2w when i use waveshareoledlcdvert waveshareoledlcd as a config the screen doesn't work!

### ISSUE THREAD

**Issue by LuckyFishGeek** [jayofelony/pwnagotchi#180]
**Describe the bug**
I can get the screen to work when I use a raspberry pi zero WH, but when I use a raspberry pi zero 2w and flash a 64 bit image the screen doesn't work.

**Comment by jayofelony** [comment]
Edit /boot/firmware/config.txt to spi0-2cs I think.
