### ISSUE TITLE
I2C Display

### ISSUE THREAD

**Issue by Xanndiane** [jayofelony/pwnagotchi#198]
Hi, I would like to know how to use the ssd1306 i2c screen? It is in the repository files, but it is not in the image.

**Comment by RasTacsko** [comment]
Hi
[I made a bash script](https://github.com/RasTacsko/Pwnagotchi-plugins/blob/main/displaydriverupdate.sh) that downloads my pwny repo with the updated display drivers, and copies it to the necessary folders, so if someone afraid to do it manually, it can be automated... Be aware that is made with chat gpt, and it is need internet connection of course, so use at your own risk, and modify as necessary...
Just create an .sh file in /home/pi or copy it with sftp and run it after chmod +x all feedbacks are welcome of course

**Comment by Xanndiane** [comment]
> Hi [I made a bash script](https://github.com/RasTacsko/Pwnagotchi-plugins/blob/main/displaydriverupdate.sh) that downloads my pwny repo with the updated display drivers, and copies it to the necessary folders, so if someone afraid to do it manually, it can be automated... Be aware that is made with chat gpt, and it is need internet connection of course, so use at your own risk, and modify as necessary... Just create an .sh file in /home/pi or copy it with sftp and run it after chmod +x all feedbacks are welcome of course

Unfortunately it doesn't work for me, I already wrote to you about it on Reddit, have you tested it yourself?

**Comment by RasTacsko** [comment]
Hi
I haven't checked up on reddit, but modified the scripta bit, there was a target directory error.
jays 2.8.9 release is using python 3.9 for the 32bit image, now the script will ask for what operating system you have and should update the necessary files and folders.
Try it again and feedback please, so I can fix the issue.

**Comment by Xanndiane** [comment]
I tested the screen outside Pwnagotchi and it works. Maybe there is some way to get the state and other data from pwnagotchi to output them through third-party code? (Not a ready-made bitmap image, but data in the form of text)

**Comment by Xanndiane** [comment]
Okay, I'll try in a few hours.

**Comment by Xanndiane** [comment]
Спасибо

**Comment by Xanndiane** [comment]
> Hi I haven't checked up on reddit, but modified the scripta bit, there was a target directory error. jays 2.8.9 release is using python 3.9 for the 32bit image, now the script will ask for what operating system you have and should update the necessary files and folders. Try it again and feedback please, so I can fix the issue.

Now its work. Thanks bro.
![IMG_20240927_201931](https://github.com/user-attachments/assets/d120b835-9b16-4762-87af-8aff00a08148)
