### ISSUE TITLE
[Question] Connect to Home WIFI instead Ethernet 

### ISSUE THREAD

**Issue by AchimGrolimund** [jayofelony/pwnagotchi#201]
you can connect the Raspy (4) via Ethernet cable to read out the data (ssh) or for the WebService.

Is it also possible to set the WIFI settings when flashing? so that the Raspi(4) always establishes a WIFI connection with the home network and you can call up the Web UI?

Or does this interfere with the scanning process of the pwnagotchi?

Best regards

**Comment by RasTacsko** [comment]
When the pwnagotchi boots up, the bettercap service is setting up the wifi to monitor mode, so it is not able to connect to any wifi networks as usual. There are workarounds if you are using a usb wifi dongle so you will have one for scanning one for regular use.

**Comment by AchimGrolimund** [comment]
that's what i thought. thanks for the quick reply.
