### ISSUE TITLE
[BUG] plugins disappear on Home Screen but remain in config file enabled

### ISSUE THREAD

**Issue by ScottishShaun123** [jayofelony/pwnagotchi#204]
**Describe the bug**

I don’t know what happened but every plugin has disappeared from the Home Screen and the plugins screen but weirdly I can see them in the web CFG page and they are enabled as they were before. I can still see all the default plugins that came with the build and they are all working as far as I’m aware. 
![IMG_2611](https://github.com/user-attachments/assets/9b7efa09-7738-4dd5-a61e-8ea170dacf26)

**To Reproduce**
Unknown 

**Expected behavior**
Custom plugins should remain active and visible on Home Screen and also plugins page. They are seen as activated in webcfg but they are not.

**Screenshots*

**Environment (please complete the following information):**
 - Pwnagotchi version jayofelenoy image 2.8.9
 - OS version 
 - Type of hardware raspberry pi zero W
 - Any additional hardware used
![IMG_2609](https://github.com/user-attachments/assets/235fd90f-286c-495b-acbc-784160a0a2ec)
![IMG_2610](https://github.com/user-attachments/assets/f8027f9f-b403-422f-bd15-67e6b28eaad4)
![IMG_2615](https://github.com/user-attachments/assets/cf3f6c60-1e98-49f3-92ac-34b38c2383c3)
![IMG_2616](https://github.com/user-attachments/assets/a39b5b2f-61bf-4389-b502-6d366ee0169e)
![IMG_2617](https://github.com/user-attachments/assets/ce5af950-ca69-41bb-8d25-19c5bd658d4f)
![IMG_2618](https://github.com/user-attachments/assets/db76fc42-0bd8-4221-a2a1-7bab943426ec)
![IMG_2619](https://github.com/user-attachments/assets/e3364c67-9068-4078-b2d5-8470c328fc2d)
![IMG_2620](https://github.com/user-attachments/assets/35d9e08c-aa3b-436f-9164-0b4f1a4ad82d)
![IMG_2621](https://github.com/user-attachments/assets/874a79b9-b7f3-44e9-802a-c820ca53a0f0)
![IMG_2622](https://github.com/user-attachments/assets/cc19ffdd-e596-4a3d-b6de-4ecf3001026c)
![IMG_2614](https://github.com/user-attachments/assets/9f33c0fd-4a73-4392-a63f-a56a2b289e3d)

**Additional context**

**Comment by jayofelony** [comment]
Whats your custom-plugin folder set to in your config.toml, and does it match with the location of the plugin files?

**Comment by ScottishShaun123** [comment]
You are the man 😅 I feel so dumb now. I’ve only went and input a git link in place of where the folder location should be when adding custom plugins. All working again. I truly appreciate all the work you do for this project. 🙏

> Whats your custom-plugin folder set to in your config.toml, and does it match with the location of the plugin files?
