### ISSUE TITLE
[BUG] when set ui.invert, display background color don't change

### ISSUE THREAD

**Issue by amenekowo** [jayofelony/pwnagotchi#208]
**Describe the bug**
When use git repo master (at this time) built pwnagotchi, ui display abnormal, `ui.invert` can't control display background color.
when `ui.invert=true`, background is black and some of the plugins' ui elements are missing (for i guess, the font is black and hidden because the background is also black).
![image](https://github.com/user-attachments/assets/4bdc9855-b96e-44f9-9a9f-01171aee5bdc)

when `ui.invert=false`, the background is black but ui elements is shown correctly.
![image](https://github.com/user-attachments/assets/f5674740-45d0-46f5-aef1-b388973bbd23)

**To Reproduce**
1. set `ui.invert` parameter in config
2. do `systemctl restart pwnagotchi` and see display change

**Expected behavior**
1. texts should be white when background is black. (i forget whether `ui.invert` true is for black or false,)
2. when set `ui.invert`, display background color should change.

**Screenshots**
see above

**Environment (please complete the following information):**
 - Pwnagotchi version: 2.9.2, but built from master (`commit 7e6d198c9be4ea0015eaf090b39382be7c85a202`)
 - OS version: Kali Rolling x86_64 (`Linux isoustick 6.10.9-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.10.9-1kali1 (2024-09-09) x86_64 GNU/Linux`)
 - Type of hardware: x86 generic (Intel x5-Z8330 Compute Stick)
 - Any additional hardware used
   - RTL8812AU for main pwning
   - u-blox 8 GPS

**Additional context**
I set `ui.display.enabled = false` because I can't use a display on x86 hardware.

if you need more info, please tell me and I will provide more :)

**Comment by jayofelony** [comment]
Do not use 2.9.2, it is not released. I cannot help you now. Use the pre built image.
