### ISSUE TITLE
Cannot ssh to Pwnagotchi

### ISSUE THREAD

**Issue by sadpulsar** [jayofelony/pwnagotchi#214]
Hello there! I have a RPI Zero W (32-bit version). I recently tried to flash the latest image of pwnagotchi into my card. I did it with the RPI Imager, but without customizing the settings section. After flashing the image I connected it to my pc via the data port with a data cable, following the instructions. The ethernet showed up and I changed the IP, Subnet etc. as it is mentioned in the tutorial. After that I tried to ssh into my pwnagotchi but I get a host unreachable error, every time I try to ping or ssh into the device. I changed cards and data cable after all that but I had the same issue again. I put my own config.toml in the boot partition and I still get the same error. My pc has linux mint xfce installed. I tried also connecting to it via the script and I still got the same behaviour. Is there some extra step that I skipped? Could it be something else?

**Comment by jayofelony** [comment]
With linux you need to run the script multiple times. Did you edit the script as the guide stated?

**Comment by sadpulsar** [comment]
Yes I did edit the script and I run it but the problem is that after the first run I get always the same error (ipv4: Address already assigned). Should I run it again even though I get this error?

**Comment by jayofelony** [comment]
No, you're fine in that case. But for linux you do not have to set up any interfaces. The script does that for you.

**Comment by sadpulsar** [comment]
Ok so there is no need to configure the interface via network manager, right? What if still after that I can't connect to my pwnagotchi?

**Comment by jayofelony** [comment]
Wrong cable, you sure it is a data cable?

**Comment by sadpulsar** [comment]
I tried 3 cables.... Is there a log file somewhere which can give me more infos?

**Comment by jayofelony** [comment]
Well you could try `lsusb` to see what is connected to USB on your pc.

**Comment by sadpulsar** [comment]
I did that and it shows up there as far as I remember...

**Comment by sadpulsar** [comment]
Ok just to verify that I didn't do something wrong here... In the script for the linux connections we need to change 2 values:
I am connected to my router via wifi with a usb adapter ( I don't know if that matters, I am just pointing it out :stuck_out_tongue: ). That's the value of the UPSTREAM_IFACE. The other value will be USB_IFACE which is the value from the ifconfig section. Is that right?

**Comment by jayofelony** [comment]
Yes, and dont forget about the starting `-` as I mentioned in the guide.

**Comment by sadpulsar** [comment]
I configured everything as mentioned in the tutorial, and the connection shows up on my pc. Even though all that happens I cannot ping the pwnagotchi.

**Comment by jayofelony** [comment]
Can you show me a screenshot `ifconfig`?

**Comment by sadpulsar** [comment]
I am just pasting the usb interface, if you want the whole screenshot let me know! 

enx662e16ee28a1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.1  netmask 255.255.255.0  broadcast 10.0.0.255
        ether 66:2e:16:ee:28:a1  txqueuelen 1000  (Ethernet)
        RX packets 1940  bytes 54668 (54.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3  bytes 504 (504.0 B)
        TX errors 2220  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by sadpulsar** [comment]
I did nothing new and I just changed cables again and it worked..... It is very weird.... But it works now.... Thanx for the support!!!

**Comment by sadpulsar** [comment]
Sadly it worked only once and then not again for a long time. I setup the device with the pwnagotchi wizard and it doesn't work again :stuck_out_tongue: . It must be some data issue cable I assume or I don't know what else.... The problem is that the one time it worked all happened really fast. Could it maybe be an sd card problem? Could it be that the card is worn out and therefore everything is happening very slow?

**Comment by jayofelony** [comment]
If it lost connection, try running the script again. It can take a couple of runs. If it doesn't say already exists it will work hopefully.

**Comment by RedwoodSec** [comment]
> No, you're fine in that case. But for linux you do not have to set up any interfaces. The script does that for you.

Wut? Why does tutorial say to do it seems still necessary on Ubuntu or it just doesn't work.
