### ISSUE TITLE
Forked dependancies?

### ISSUE THREAD

**Issue by muang0** [jayofelony/pwnagotchi#215]
Why does the build image pull from a forked bettercap?

**Comment by jayofelony** [comment]
Because I added PRs that the original didn't, sonce it was abandoned for quite some years. And rhis way I could experiment with removing/adding functions.

**Comment by jayofelony** [comment]
Closing this as it isnt an issue, next time please use discussions or something else.

**Comment by muang0** [comment]
Bettercap isn't abandoned -> https://github.com/bettercap/bettercap
