### ISSUE TITLE
Update onlinehashcrack.py

### ISSUE THREAD

**Issue by g4h4** [jayofelony/pwnagotchi#221]
Kindly update module onlinehashcrack.py (pwnagotchi/plugins/default/onlinehashcrack.py)
New API documentation : https://www.onlinehashcrack.com/how-developpers-api-documentation.php
and https://www.onlinehashcrack.com/how-developpers-public-api-documentation.php

**Comment by wpa-2** [comment]
> Kindly update module onlinehashcrack.py (pwnagotchi/plugins/default/onlinehashcrack.py) New API documentation : https://www.onlinehashcrack.com/how-developpers-api-documentation.php and https://www.onlinehashcrack.com/how-developpers-public-api-documentation.php

You could always do that and create a PR, some how I don't think this is top priority currently.

**Comment by g4h4** [comment]
As far as i understand, new changes are : listing ongoing tasks and add 'wpax' hashes.
