### ISSUE TITLE
gdrivesync plugin not working

### ISSUE THREAD

**Issue by diytech1** [jayofelony/pwnagotchi#235]
**Describe the bug**

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Pwnagotchi version
 - OS version
 - Type of hardware
 - Any additional hardware used

**Additional context**

**Comment by jayofelony** [comment]
https://github.com/jayofelony/pwnagotchi/blob/noai/README-google.md

Closing this as no further context was provided.
