### ISSUE TITLE
Wpa-Sec Force Upload

### ISSUE THREAD

**Issue by MimoAW** [jayofelony/pwnagotchi#236]
I don't know if this is where I do this but I would be nice if there is a force upload button for wpa-sec. Thank you!

**Comment by jayofelony** [comment]
As long as your device has internet, through BT-Tether or USB it will automatically upload to wpa-sec when a valid handshake has been captured. Even when in AUTO/AI/AT.

**Comment by MimoAW** [comment]
Okay that's fine then. Thank you!

**Comment by sakkarose** [comment]
You could trigger it again by changing between Manual and Auto mode.
