### ISSUE TITLE
Bettercap web UI

### ISSUE THREAD

**Issue by MimoAW** [jayofelony/pwnagotchi#238]
**Describe the bug**
I can not connect to the bettercap web UI if I refreshed it while the pwnagotchi is rebooting I tried on virtual machines and different computers and different web browsers and it just won't let me in the pwnagotchi web UI does work though could there be a way to fix it in 2.9.2?
**To Reproduce**
1. Press refresh multiple times while the pwnagotchi is rebooting

**Expected behavior**
I can use the web UI again

**Screenshots**
<img width="1049" alt="Screenshot 2024-12-03 at 6 33 42 pm" src="https://github.com/user-attachments/assets/bafe2ec1-95fe-4ace-8a1f-743e6bdbb32a">
<img width="1049" alt="Screenshot 2024-12-03 at 6 33 31 pm" src="https://github.com/user-attachments/assets/18399a42-eafa-490f-8298-0b3bc57f0fae">

**Environment (please complete the following information):**
 - Pwnagotchi version = 2.8.9
 - OS version = Mac Sequoia latest, kali latest, fedora latest and windows 10 latest
 - Type of hardware =Pi 4b
 - Any additional hardware used =None

Thank you!

**Comment by MimoAW** [comment]
Okay thank you so much!

**Comment by MimoAW** [comment]
Sorry to reopen this but I just noticed yesterday, I made a typo I'm not on 2.8.2 I'm on 2.8.9 and it still doesn't work should I just wait until 2.9.2? Thank you!

**Comment by jayofelony** [comment]
When you can see http://10.0.0.2:8080 can you see http://10.0.0.2:80 ?

Can you show your config.toml, because bettercap ui works, just not for you. Out of thousands of users, you are the only one experiencing this issue.

**Comment by MimoAW** [comment]
No i cant see http://10.0.0.2:80 I don't know if the photos 
in the other comment will help. He is my config

main.name = "MilosPwnagotchi"
main.plugins.bt-tether.enabled = true
main.plugins.bt-tether.devices.android-phone.enabled = true
main.plugins.bt-tether.devices.android-phone.mac = "D4:3A:2C:BF:03:3A"
main.plugins.bt-tether.devices.android-phone.search_order = 1
main.plugins.bt-tether.devices.android-phone.ip = "192.168.44.44"
main.plugins.bt-tether.devices.android-phone.netmask = 24
main.plugins.bt-tether.devices.android-phone.interval = 1
main.plugins.bt-tether.devices.android-phone.scantime = 10
main.plugins.bt-tether.devices.android-phone.max_tries = 500
main.plugins.bt-tether.devices.android-phone.share_internet = true
main.plugins.bt-tether.devices.android-phone.priority = 1

main.plugins.bt-tether.devices.ios-phone.enabled = false
main.plugins.bt-tether.devices.ios-phone.search_order = 2
main.plugins.bt-tether.devices.ios-phone.mac = ""
main.plugins.bt-tether.devices.ios-phone.ip = "172.20.10.6"
main.plugins.bt-tether.devices.ios-phone.netmask = 24
main.plugins.bt-tether.devices.ios-phone.interval = 5
main.plugins.bt-tether.devices.ios-phone.scantime = 20
main.plugins.bt-tether.devices.ios-phone.max_tries = 0
main.plugins.bt-tether.devices.ios-phone.share_internet = true
main.plugins.bt-tether.devices.ios-phone.priority = 999

main.plugins.auto-update.enabled = true
main.plugins.auto-update.install = true
main.plugins.auto-update.interval = 1

main.plugins.fix_services.enabled = true

main.plugins.gdrivesync.enabled = false
main.plugins.gdrivesync.backupfiles = [ "",]
main.plugins.gdrivesync.backup_folder = "PwnagotchiBackups"

main.plugins.gpio_buttons.enabled = false

main.plugins.gps.enabled = true
main.plugins.gps.speed = 9600
main.plugins.gps.device = "/dev/ttyACM0"

main.plugins.grid.enabled = true
main.plugins.grid.report = true

main.plugins.logtail.enabled = true
main.plugins.logtail.max-lines = 10000

main.plugins.memtemp.enabled = false
main.plugins.memtemp.scale = "celsius"
main.plugins.memtemp.orientation = "horizontal"

main.plugins.net-pos.enabled = false
main.plugins.net-pos.api_key = "test"

main.plugins.onlinehashcrack.enabled = false
main.plugins.onlinehashcrack.email = ""
main.plugins.onlinehashcrack.dashboard = ""
main.plugins.onlinehashcrack.single_files = false

main.plugins.pisugar2.enabled = false
main.plugins.pisugar2.shutdown = 5
main.plugins.pisugar2.sync_rtc_on_boot = false

main.plugins.session-stats.enabled = true
main.plugins.session-stats.save_directory = "/var/tmp/pwnagotchi/sessions/"

main.plugins.ups_hat_c.enabled = false
main.plugins.ups_hat_c.label_on = true
main.plugins.ups_hat_c.shutdown = 5
main.plugins.ups_hat_c.bat_x_coord = 140
main.plugins.ups_hat_c.bat_y_coord = 0

main.plugins.ups_lite.enabled = false
main.plugins.ups_lite.shutdown = 2

main.plugins.webcfg.enabled = true

main.plugins.webgpsmap.enabled = false

main.plugins.wigle.enabled = true
main.plugins.wigle.api_key = "6fb90c7f75cbc485ca0d37822bc7b7a8"
main.plugins.wigle.donate = false

main.plugins.wpa-sec.enabled = true
main.plugins.wpa-sec.api_key = "47b189703b1b786fd2731b6a60b99d71"
main.plugins.wpa-sec.api_url = "https://wpa-sec.stanev.org"
main.plugins.wpa-sec.download_results = false

main.plugins.wardriver.enabled = false

main.plugins.tweak_view.enabled = true

main.plugins.internet-connection.enabled = true

main.plugins.handshakes-dl.enabled = true

main.plugins.aircrackonly.enabled = true

main.plugins.instattack.enabled = true

main.lang = "en"
main.whitelist = [
 "EXAMPLE_NETWORK",
 "ANOTHER_EXAMPLE_NETWORK",
 "fo:od:ba:be:fo:od",
 "fo:od:ba",
]
main.confd = "/etc/pwnagotchi/conf.d/"
main.custom_plugin_repos = [
 "https://github.com/jayofelony/pwnagotchi-torch-plugins/archive/master.zip",
 "https://github.com/tisboyo/pwnagotchi-pisugar2-plugin/archive/master.zip",
 "https://github.com/nullm0ose/pwnagotchi-plugin-pisugar3/archive/master.zip",
 "https://github.com/Sniffleupagus/pwnagotchi_plugins/archive/master.zip",
 "https://github.com/NeonLightning/pwny/archive/master.zip",
 "https://github.com/marbasec/UPSLite_Plugin_1_3/archive/master.zip",
]
main.custom_plugins = "/usr/local/share/pwnagotchi/custom-plugins/"
main.plugin.gdrivesync.interval = 1

main.iface = "wlan0mon"
main.mon_start_cmd = "/usr/bin/monstart"
main.mon_stop_cmd = "/usr/bin/monstop"
main.mon_max_blind_epochs = 50
main.no_restart = false
main.log.path = "/etc/pwnagotchi/log/pwnagotchi.log"
main.log.rotation.enabled = true
main.log.rotation.size = "10M"

ai.enabled = true
ai.path = "/root/brain.nn"
ai.laziness = 0.1
ai.epochs_per_episode = 50
ai.params.gamma = 0.99
ai.params.n_steps = 1
ai.params.vf_coef = 0.25
ai.params.ent_coef = 0.01
ai.params.max_grad_norm = 0.5
ai.params.learning_rate = 0.001
ai.params.verbose = 1

personality.advertise = true
personality.deauth = true
personality.associate = true
personality.channels = [
 1,
 5,
 6,
 8,
 9,
 10,
 11,
 44,
 52,
 56,
 64,
 100,
 108,
 112,
 120,
 132,
 136,
 140,
 165,
]
personality.min_rssi = -78
personality.ap_ttl = 264
personality.sta_ttl = 254
personality.recon_time = 30
personality.max_inactive_scale = 6
personality.recon_inactive_multiplier = 2
personality.hop_recon_time = 7
personality.min_recon_time = 6
personality.max_interactions = 6
personality.max_misses_for_recon = 5
personality.excited_num_epochs = 20
personality.bored_num_epochs = 23
personality.sad_num_epochs = 13
personality.bond_encounters_factor = 20000
personality.throttle_a = 0.4
personality.throttle_d = 0.9
personality.clear_on_exit = true

ui.invert = false
ui.fps = 0
ui.font.name = "DejaVuSansMono"
ui.font.size_offset = 0

ui.faces.look_r = "( ⚆_⚆)"
ui.faces.look_l = "(☉_☉ )"
ui.faces.look_r_happy = "( ◕‿◕)"
ui.faces.look_l_happy = "(◕‿◕ )"
ui.faces.sleep = "(⇀‿‿↼)"
ui.faces.sleep2 = "(≖‿‿≖)"
ui.faces.awake = "(◕‿‿◕)"
ui.faces.bored = "(-__-)"
ui.faces.intense = "(°▃▃°)"
ui.faces.cool = "(⌐■_■)"
ui.faces.happy = "(•‿‿•)"
ui.faces.excited = "(ᵔ◡◡ᵔ)"
ui.faces.grateful = "(^‿‿^)"
ui.faces.motivated = "(☼‿‿☼)"
ui.faces.demotivated = "(≖__≖)"
ui.faces.smart = "(✜‿‿✜)"
ui.faces.lonely = "(ب__ب)"
ui.faces.sad = "(╥☁╥ )"
ui.faces.angry = "(-_-')"
ui.faces.friend = "(♥‿‿♥)"
ui.faces.broken = "(☓‿‿☓)"
ui.faces.debug = "(#__#)"
ui.faces.upload = "(1__0)"
ui.faces.upload1 = "(1__1)"
ui.faces.upload2 = "(0__1)"
ui.faces.png = false
ui.faces.position_x = 0
ui.faces.position_y = 34

ui.web.enabled = true
ui.web.address = "::"
ui.web.username = "Admin"
ui.web.password = "Mimo Wills"
ui.web.origin = ""
ui.web.port = 8080
ui.web.on_frame = ""

ui.display.enabled = false
ui.display.rotation = 180
ui.display.type = "waveshare_4"

bettercap.handshakes = "/root/handshakes"
bettercap.silence = [
 "ble.device.new",
 "ble.device.lost",
 "ble.device.disconnected",
 "ble.device.connected",
 "ble.device.service.discovered",
 "ble.device.characteristic.discovered",
 "wifi.client.new",
 "wifi.client.lost",
 "wifi.client.probe",
 "wifi.ap.new",
 "wifi.ap.lost",
 "mod.started",
]

fs.memory.enabled = true
fs.memory.mounts.log.enabled = true
fs.memory.mounts.log.mount = "/etc/pwnagotchi/log/"
fs.memory.mounts.log.size = "50M"
fs.memory.mounts.log.sync = 60
fs.memory.mounts.log.zram = true
fs.memory.mounts.log.rsync = true

fs.memory.mounts.data.enabled = true
fs.memory.mounts.data.mount = "/var/tmp/pwnagotchi"
fs.memory.mounts.data.size = "10M"
fs.memory.mounts.data.sync = 3600
fs.memory.mounts.data.zram = true
fs.memory.mounts.data.rsync = true

I'm so sorry about all of this

**Comment by MimoAW** [comment]
Okay of course. Thank you for your help!
