### ISSUE TITLE
Unable to start external wifi adapter RTL8812au (Tenda U12)

### ISSUE THREAD

**Issue by UrbanTrip96** [jayofelony/pwnagotchi#242]
I can't get the external adapter to work. Without installing the drivers, my pwnagotchi doesn't see the adapter at all and doesn't understand what it is. After installing the drivers from the aircrack-ng repository, it starts seeing it, but can't switch it to monitor mode. I disabled the internal Wi-Fi in dtoverlay, tried using the ext-wifi.py plugin, tried to enter the commands manually, but all to no avail. I haven't found a single working instruction on the Internet. When using the 1.5.5FIX image, my adapter works without problems. Tell me what to do? Please, help me.
My device : Rpi0w2 
2.8.9 64

**Comment by jayofelony** [comment]
RTL8812AU isn't supported anymore in newer kernels, no fix unfortunately.
