### ISSUE TITLE
[BUG] I am getting a dependency error prctl

### ISSUE THREAD

**Issue by SailAway33** [jayofelony/pwnagotchi#246]
I attempted to update the packages after the auto upgrade process. The packages would not update from the UI at 10.0.0.2:8080 the UI just hung. I then sshed into the pwnagotchi and attempted to update the packages through the terminal. At that point it crashed the session. I further went in to check the to see if it would recheck the update and even running version I am getting the following

**To Reproduce**
`pwnagotchi@pwnagotchi:~ $ sudo pwnagotchi --check-update
Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 15, in <module>
    from pwnagotchi.plugins import cmd as plugins_cmd
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/__init__.py", line 9, in <module>
    import prctl
ModuleNotFoundError: No module named 'prctl'

pwnagotchi@pwnagotchi:~ $ sudo pwnagotchi --version
Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 15, in <module>
    from pwnagotchi.plugins import cmd as plugins_cmd
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/__init__.py", line 9, in <module>
    import prctl
ModuleNotFoundError: No module named 'prctl'
`

 - Pwnagotchi version
 - 2.9.2
 - this repo
 - Zero 2W
 - Any additional hardware used

**Additional context**
I was able to fix it partially through apt install python3-prctl

**Comment by jayofelony** [comment]
Dont auto update, full reflash required!
