### ISSUE TITLE
Mention of "deep reinforcment learning" in project description

### ISSUE THREAD

**Issue by awulicja** [jayofelony/pwnagotchi#250]
**Is your feature request related to a problem? Please describe.**
Since 2.9.2 apparently removed the AI mode is it still accurate to describe the project as "Deep Reinforcement Learning instrumenting bettercap for WiFi pwning. "? Specifically the "Deep Reinforcement Learning" part feels off.

**Describe the solution you'd like**
I believe it's better to come up with a more accurate phrase to describe a project, I'm quite bad at inventing those however, so I've got nothing.

**Describe alternatives you've considered**
Not to do anything -- but then it is somewhat confusing, inconsistent and (big maybe) a bit deceiving.

**Comment by jayofelony** [comment]
Yes, you are right. I will edit that as soon as possible haha.

**Comment by nasiralamreeki** [comment]
@jayofelony might even be worth a rename since AI is stripped out and that was the chief feature of upstream.
