### ISSUE TITLE
Send terminal commands from WebUI

### ISSUE THREAD

**Issue by michaelbapst** [jayofelony/pwnagotchi#255]
I was wondering if there was a way to send terminal commands through the WebUI. This would be a real help when Pwnagotchi is connected to the phone via bluetooth. Or a button at the bottom of the WebUI that basically performs the same function as 
`pwnagotchi --clear`
either would be great.

**Comment by wpa-2** [comment]
whats wrong with using terminal ? 
apple/android both have options.

**Comment by michaelbapst** [comment]
I haven't been able to ssh with a terminal app via bluetooth, I figured it wasn't possible because bluetooth can be weird like that. Still would make a nice enhancement, be able to do simple terminal commends from the WebUI.

**Comment by wpa-2** [comment]
> I haven't been able to ssh with a terminal app via bluetooth, I figured it wasn't possible because bluetooth can be weird like that. Still would make a nice enhancement, be able to do simple terminal commends from the WebUI.

ssh over bluetooth works without issues, you just use the bluetooth IP to connect.

**Comment by jayofelony** [comment]
Use a simple as like Termius for that. Closing.
