### ISSUE TITLE
Bluetooth Tethering Fails to Auto-Connect and Disconnects Intermittently

### ISSUE THREAD

**Issue by Havivw** [jayofelony/pwnagotchi#257]
### Contact Details

Havivv1305@gmail.com

### What happened?

Bluetooth tethering did not connect automatically during the initial setup; I had to use bluetoothctl to manually connect. However, it disconnects after some time.

### Version

2.9.2 (64bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jayofelony** [comment]
New bt tether is under development.
