### ISSUE TITLE
New and no Idea

### ISSUE THREAD

**Issue by Penetrationpasi-hub** [jayofelony/pwnagotchi#260]
Hi, I just bought a Pwnagotchi and downloaded the latest image. However, when I plug the Pwnagotchi into my Windows 11 (64-bit) PC, nothing happens, even if I wait more than 10 minutes. There should be an Ethernet interface appearing, right? Why isn't that happening? I’m using an RPi Zero 2 W with a Waveshare 2.13 V4 display. I used Raspberry Pi OS as described in the setup guide. I also downloaded the latest RNDIS driver from https://pwnagotchi.org/getting-started/software/index.html, but when I try to install it, Windows tells me the best driver is already installed, but nothing happens.

**Comment by jayofelony** [comment]
Most probable cause is the USB cable used not being able to send data.

**Comment by Pastel1130** [comment]
I'm having a similar problem but I have a data cable

**Comment by wpa-2** [comment]
> I'm having a similar problem but I have a data cable

Uninstall the current driver and then install the mod version.

**Comment by NuscoMix** [comment]
I had the same problem, I put a microUSB - USB Type C cable. The connection problem is gone

**Comment by Pastel1130** [comment]
Yeah I'm having the same issue. The Pwan comes on and works, but doesn't come up in Device Manager as anything.

**Comment by jayofelony** [comment]
Closing this as this is not a software related issue to Pwnagotchi, most cables advertised as data cable are actually not a data cable.

**Comment by Penetrationpasi-hub** [comment]
Hi,

no, it's not the data cable. I used an adapter to USB-C, and I was able to transfer as much data as I wanted.
It also seems that I'm not the only one struggling with this. So, where should I ask this question instead?

My Windows PC just doesn't recognize the Pwnagotchi, no matter what I do. I tried the setup guide three times.
There isn't even the usual sound when you plug in an USB Device, just  nothing happens.

LG Pascal Range

________________________________
Von: Jayofelony ***@***.***>
Gesendet: Samstag, 28. Dezember 2024 15:56
An: jayofelony/pwnagotchi ***@***.***>
Cc: Penetrationpasi-hub ***@***.***>; Author ***@***.***>
Betreff: Re: [jayofelony/pwnagotchi] New and no Idea (Issue #260)


Closing this as this is not a software related issue to Pwnagotchi, most cables advertised as data cable are actually not a data cable.

**Comment by Pastel1130** [comment]
@jayofelony could you provide us with a link to a data cable that works?
