### ISSUE TITLE
When using share internet connection script no joy

### ISSUE THREAD

**Issue by Awo16** [jayofelony/pwnagotchi#261]
trying to get my gotchi to connect to internet over usb but can't get it to work. I tried all methods with no joy. any solutions to this problem in the works? I'm using macOS btw. thanks :)

**Comment by wpa-2** [comment]
Try this 
https://pwnagotchi.org/getting-started/first-run-mac/index.html

Tested and works fine.

**Comment by jayofelony** [comment]
Any updates on this @Awo16, is it working now? Otherwise please close the issue.

**Comment by Awo16** [comment]
Tried multiple different ways, still no luck.
