### ISSUE TITLE
Screen Doesn't Go Blank After Power Off via Web UI

### ISSUE THREAD

**Issue by languagemaniac** [jayofelony/pwnagotchi#266]
Hi,

In version 2.9.2, when I powered off the device via the web UI, the screen would go blank as expected.

However, in the current version, the screen stays frozen on the last image instead of going blank. Is this a bug, or has the behavior been changed intentionally?

Any advice or workaround to make the screen go blank again would be appreciated.

Thanks!

**Comment by jayofelony** [comment]
Intentional. Use `sudo pwnagotchi --clear` to clear display.
