### ISSUE TITLE
No plugins 2.9.3 image

### ISSUE THREAD

**Issue by AlienMajik** [jayofelony/pwnagotchi#268]
It no longer has a available plugins or custom plugins: sudo pwnagotchi plugins list does not work. Pwnkill does not work either. Also there are 2 handshake folders being created one in /root and the other at /home/pi

**Comment by wpa-2** [comment]
![2024-12-22 08_25_47-pi@pwny-bugfind_ ~](https://github.com/user-attachments/assets/70f0e70e-2cab-490d-a213-a84b674944f8)

default folder now is /home/pi/handshakes/ 

pwnkill works just fine. 
![2024-12-22 08_27_19-pi@pwny-bugfind_ ~](https://github.com/user-attachments/assets/87103afb-5b70-44fa-b59a-1306f76cb006)

check debug 
```
sudo systemctl stop pwnagotchi.service
sudo pwnagotchi --debug 
```

**Comment by wpa-2** [comment]
@jayofelony  looks like this has been sorted maybe.

**Comment by AlienMajik** [comment]
Is this on the 2.9.3 image?

**Comment by wpa-2** [comment]
> Is this on the 2.9.3 image?

Yes it is.

**Comment by AlienMajik** [comment]
Not sure what happened then it just would not work for so i just reflashed back to 2.9.2 and it started working

**Comment by wpa-2** [comment]
> Not sure what happened then it just would not work for so i just reflashed back to 2.9.2 and it started working

try the new image https://github.com/jayofelony/pwnagotchi/releases/tag/v2.9.3-2

this can be closed though.

**Comment by Agnar319** [comment]
I've flashed probably 10 times, with 4 different SDs on 2 different Pis and can't, for the life of me, get plugins to work either. Also, probably just a me issue, but i cant get output to any of my displays or web ui.

**Comment by wpa-2** [comment]
> I've flashed probably 10 times, with 4 different SDs on 2 different Pis and can't, for the life of me, get plugins to work either. Also, probably just a me issue, but i cant get output to any of my displays or web ui.

As its a different issue please create your own. 
check debug, but remember a lot of the plugins will be outdated now as there's been a good few updates/changes.

**Comment by AlienMajik** [comment]
Getting same errors on 2.9.3-2 image. After rebooting most files disappeared going to reflash and run it for awhile and see what happens![image](https://github.com/user-attachments/assets/f8270148-bbd7-4f14-b3ee-37a3709cfd64)![image](https://github.com/user-attachments/assets/aea58d8a-951d-4d87-a8dc-a6a02345eeda)

**Comment by AlienMajik** [comment]
Yea thats weird after flashing the second time it is now working? How who knows? Problem fixed

**Comment by wpa-2** [comment]
The wiki clear states the user PI is needed for the new versions due to permission issues. 
You are going to need to reflash.

**Comment by AlienMajik** [comment]
What do you mean by that? When I first boot and it asks me to give the host name just put in pi instead of a custom name?

**Comment by wpa-2** [comment]
> What do you mean by that? When I first boot and it asks me to give the host name just put in pi instead of a custom name?

I'm talking about username not host name. 
Please check the wiki and see the screenshots showing the settings you need on RPI imager.

**Comment by AlienMajik** [comment]
Ok I did that named it pi and it only works with my AWUS036AXM and not with the stock wifi module of my pi 5 os it because it can now scan for 6ghz wifi networks?

**Comment by AlienMajik** [comment]
It is now working on both it just takes awhile for it to activate the tx power on the stock pi 5 wifi module
