### ISSUE TITLE
[Bug]: bluetooth web ui

### ISSUE THREAD

**Issue by saurabhkumar1346** [jayofelony/pwnagotchi#269]
### Contact Details

saurabhkumar1346@gmail.com

### What happened?

web ui working fine in pc 10.0.0.2 but in bluetooth cant access web ui at 192.168.44.4 (raspberry pi zero w 32bit)
![Screenshot (3)](https://github.com/user-attachments/assets/cc9d8426-cbaa-4dd8-968d-a6f77d399f7b)

### Version

2.9.3-2 (32bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wpa-2** [comment]
https://github.com/jayofelony/pwnagotchi/wiki/Step-4-Customization#bt-tethering

Your config is wrong,  check out the wiki.

**Comment by renewedbullet** [comment]
https://github.com/jayofelony/pwnagotchi/wiki/Step-4-Customization
