### ISSUE TITLE
[Bug]: Not loading pwnagotchi on the 2.9.3-2

### ISSUE THREAD

**Issue by RawrUniversal** [jayofelony/pwnagotchi#270]
### What happened?

Its not loading pwnagotchi and cant get the current version.
This is with a new flash.

"-bash: /home/pi/.pwn/lib/python3.11/site-packages/pwnagotchi/_version.py: No such file or directory"
![image](https://github.com/user-attachments/assets/76f2dfce-adb2-4bde-bb1b-b80f77adc1ef)

### Version

2.9.3-2 (64bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wpa-2** [comment]
You need to reflash and only use pi as the user, they docs mention this.

**Comment by RawrUniversal** [comment]
ah my bad.
