### ISSUE TITLE
BLUE SCREEN OF DEATH

### ISSUE THREAD

**Issue by PRADEEPDHIBAR** [jayofelony/pwnagotchi#271]
When i connect my raspberry pi zero 2w to pc for ethernet . It's recognised the driver rndis but always goes to blue screen of death.
 Window 11 pro
Raspberry pi zero 2w 

Is there any solution for this?

**Comment by wpa-2** [comment]
When you say ethernet us that via and usb eth adapter or a straight usb cable.

**Comment by PRADEEPDHIBAR** [comment]
Straight usb cable

**Comment by wpa-2** [comment]
> Straight usb cable

Good chance it's the usb driver you have installed.

**Comment by PRADEEPDHIBAR** [comment]
> > Straight usb cable
> 
> Good chance it's the usb driver you have installed.

 Rndis driver was pre-installed with Windows in my PC.

**Comment by wpa-2** [comment]
Install the MOD driver that's on the wiki.

**Comment by wpa-2** [comment]
> > Install the MOD driver that's on the wiki.
> 
> I have also installed that but it is not getting installed, it is written in it that the best driver is already installed. https://modclouddownloadprod.blob.core.windows.net/shared/mod-duo-rndis.zip

Maybe uninstall it first.

**Comment by PRADEEPDHIBAR** [comment]
> > > Install the MOD driver that's on the wiki.
> > 
> > 
> > I have also installed that but it is not getting installed, it is written in it that the best driver is already installed. https://modclouddownloadprod.blob.core.windows.net/shared/mod-duo-rndis.zip
> 
> Maybe uninstall it first.

How do I uninstall it? I don't even get time to uninstall it. As soon as I open the device manager, the blue screen of death appears.

**Comment by wpa-2** [comment]
That's not really an issue for this github, but go to device manager find it and uninstall you may need to view hidden devices.

**Comment by PRADEEPDHIBAR** [comment]
> That's not really an issue for this github, but go to device manager find it and uninstall you may need to view hidden devices.

I have tried 20 times to get at least some time to open the device manager and uninstall it. But every time the blue screen of death comes immediately

**Comment by PRADEEPDHIBAR** [comment]
> That's not really an issue for this github, but go to device manager find it and uninstall you may need to view hidden devices.

Ok, I uninstalled the driver and after that the PC was not going into BSOD, but as soon as I reinstalled the mod driver, the PC again started going into BSOD

**Comment by wpa-2** [comment]
> > That's not really an issue for this github, but go to device manager find it and uninstall you may need to view hidden devices.
> 
> I have tried 20 times to get at least some time to open the device manager and uninstall it. But every time the blue screen of death comes immediately

dont plugin the pizero then

**Comment by PRADEEPDHIBAR** [comment]
> > > That's not really an issue for this github, but go to device manager find it and uninstall you may need to view hidden devices.
> > 
> > 
> > I have tried 20 times to get at least some time to open the device manager and uninstall it. But every time the blue screen of death comes immediately
> 
> dont plugin the pizero then

What should I do now? I uninstalled and reinstalled the driver.

**Comment by wpa-2** [comment]
try plugging in the pizero and also try a different slot.

**Comment by PRADEEPDHIBAR** [comment]
Thanks now working

**Comment by wpa-2** [comment]
> Thanks now working

Please now its sorted.
