### ISSUE TITLE
[Bug]: No Eth0 internet access, even though SSH is working

### ISSUE THREAD

**Issue by flippinsweetdude** [jayofelony/pwnagotchi#272]
### Contact Details

aaron@flippinsweetdude.com

### What happened?

Fresh install of hot fix version [2.9.3-2](https://github.com/jayofelony/pwnagotchi/releases/tag/v2.9.3-2)

No modifications / installs / custom plugins or any changes.   Plugged in RasPi 4 into network and boot up.   RasPi was able to get IP address successfully, and SSH with default user/pass works successfully.

command line : ping 8.8.8.8

Results : 
![image](https://github.com/user-attachments/assets/6cbf1868-6cd5-4955-ae7b-890256670916)

Note this routes out from 10.0.0.2

command line : sudo netstat -nr

![image](https://github.com/user-attachments/assets/6f741752-f275-49a9-9f8f-8bc82587f060)

Note line 3 has no gateway 

command line :  sudo nmcli connection down usb0

![image](https://github.com/user-attachments/assets/1605abf3-cb9f-4c53-a402-40da20d70467)

then command line : sudo netstat -nr

Results : 
![image](https://github.com/user-attachments/assets/31630106-5a39-4e0b-9533-b69b4f057855)

Then ping 8.8.8.8

Results : 
![image](https://github.com/user-attachments/assets/c6d16d4e-3f44-4991-9ea4-883c8a10422e)

### Version

2.9.3-2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jayofelony** [comment]
> Note line 3 has no gateway

It has, it's the top one. It's a matter of wrong routing I think. I'll see what I can do.

**Comment by flippinsweetdude** [comment]
output of IP -4 route is : 

![image](https://github.com/user-attachments/assets/cbd91e61-8033-4615-b10a-66045bfd8b5c)

**Comment by jayofelony** [comment]
`sudo nmcli connection modify eth0 ip4.route-metric 100`

try this, see if that helps

**Comment by flippinsweetdude** [comment]
Error: invalid or not allowed setting 'ip4': 'ip4' not among [connection, 802-3-ethernet (ethernet), 802-1x, dcb, sriov, ethtool, match, ipv4, ipv6, hostname, tc, proxy].

**Comment by jayofelony** [comment]
Yeah, typo -> should be ipv4. edited previous comment.

**Comment by flippinsweetdude** [comment]
should be ipv4

**Comment by flippinsweetdude** [comment]
![image](https://github.com/user-attachments/assets/67055969-a5e3-49c6-9c54-56e557001e3a)

**Comment by jayofelony** [comment]
also run:

`sudo nmcli connection reload && sudo systemctl restart NetworkManager` afterwards.

**Comment by flippinsweetdude** [comment]
That worked.

**Comment by flippinsweetdude** [comment]
Perfect

![image](https://github.com/user-attachments/assets/5dbff0b8-079d-40ce-8f29-3716a81fd445)

**Comment by flippinsweetdude** [comment]
ip -4 route : 


![image](https://github.com/user-attachments/assets/b84e9575-30e3-44f2-a205-98270cb9cf96)

**Comment by jayofelony** [comment]
Ok, I'll add the route-metric to the connection profiles.
