### ISSUE TITLE
[Bug]: USB dongles are not working

### ISSUE THREAD

**Issue by Delurkdotcom** [jayofelony/pwnagotchi#274]
### What happened?

Hi,
I am using a Raspberry Pi Zero 2W with a Waveshare 4 screen, all powered by a PiSugar3. Everything works fine without any dongle. However, when I try to use my dongles separately, either they are not detected by the `lsusb` command, or the Pwnagotchi gets stuck on "Reading last session logs" during startup, which requires a firmware reflash to restore functionality.  

The dongles I am trying to use:  
- Alfa AWUS036AXM  
- VK-172 GPS Ublox7  

The configurations used:  
- `dtoverlay=disable-wifi` in `config.txt`  
-  
```
main.plugins.gps.enabled = true
main.plugins.gps.speed = 9600
main.plugins.gps.device = "/dev/ttyUSB0"
```  
in `config.toml`.  

### Version

2.9.3-2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wpa-2** [comment]
Your gps device is wrong it won't be /dev/ttyUSB it should be something like ACM0 maybe but if you search you will find it.

**Comment by Delurkdotcom** [comment]
Yes, that was an example configuration, but in any case, I don't see it listed with `lsusb`, and it's also not present in `/dev/`.

**Comment by wpa-2** [comment]
> Yes, that was an example configuration, but in any case, I don't see it listed with `lsusb`, and it's also not present in `/dev/`.

How are you connecting both devices and which socket are you using?

**Comment by wpa-2** [comment]
![2024-12-24 10_04_10-pi@bugfix_ ~](https://github.com/user-attachments/assets/3cba6b09-7cfe-4b4a-bb92-8187a35d5b1d)
As you can see the pi can see the devices connected.

**Comment by Delurkdotcom** [comment]
In the photo, you can see the cables I am using; they are USB female to micro-USB cables. In the terminal screenshot, `lsusb` does not list the Alfa interface connected to the micro-USB port, while the other port is being used for communication via my PC's USB interface over SSH.
![image_0003](https://github.com/user-attachments/assets/008ef595-8f61-47b4-84d1-4ebb9edaf593)
![lsusb](https://github.com/user-attachments/assets/08bdf96d-326d-4d70-a730-9967db20f9d6)

**Comment by wpa-2** [comment]
Your trying to get data from a power only port, your going to need a multi adaptor for this to work.

Usn dongles only work via the left isb slot.

**Comment by Delurkdotcom** [comment]
So, it's just a hardware issue then? Thank you, it seems so simple. Do I need a hub? A self-powered hub? A multiport adapter? Could you provide an example, please?

**Comment by jayofelony** [comment]
Closing this as it's clearly user error, no bug whatsoever. Open a discussion to talk about hardware.

**Comment by Delurkdotcom** [comment]
Also, how can I fix the "Reading last session logs" issue? I’ve already tried `sudo rm -R /etc/pwnagotchi/log*`, but it doesn’t work. I have to erase and reflash the firmware to get rid of this problem.

**Comment by wpa-2** [comment]
> Also, how can I fix the "Reading last session logs" issue? I’ve already tried `sudo rm -R /etc/pwnagotchi/log/*`, but it doesn’t work. I have to erase and reflash the firmware to get rid of this problem.

Check debug and read the wiki, My guess is something you have done is causing an issue. 
But that really isn't for git hub.
