### ISSUE TITLE
Flashing new release 2.9.3-2

### ISSUE THREAD

**Issue by scansonic** [jayofelony/pwnagotchi#277]
After the flash and the first run, everything was tuned as usual. At the second start, nothing was normally functional.
Release: https://github.com/jayofelony/pwnagotchi/releases/download/v2.9.3-2/pwnagotchi-64bit.img.xz
Board: Raspberry PI 0 2W
Flasher: (as always) raspberry pi Imager
Is it an error, or is it my stupidity?

Screenshots:
![Screenshot 2024-12-26-1](https://github.com/user-attachments/assets/fdc7752a-843f-43e3-9d14-b4fd7e151e42)
![Screenshot 2024-12-26-2](https://github.com/user-attachments/assets/c5789250-f82b-4199-9d80-a80b89cf79d2)
![Screenshot 2024-12-26-3](https://github.com/user-attachments/assets/ee8b3036-9094-413c-a360-a39a3cb045b6)
![Screenshot 2024-12-26-4](https://github.com/user-attachments/assets/9865aa95-51cb-4a5c-9236-58ef8636d5cc)

Best regards, scansonic.

**Comment by wpa-2** [comment]
Are per the instructions on the wiki you need to flash with the user PI only, once you reflash your issues should be sorted.

**Comment by Linkatplug** [comment]
Don't put a custom user. You need to re-lash with the default user and change the password afterwards. It is possible to rename the home file, but this can generate errors later. I advise you to keep the user pi and change the password.

**Comment by scansonic** [comment]
In the previous release, there was no such restriction. I changed the settings and everything worked fine.  I will go reflash and test as PI user.

**Comment by Linkatplug** [comment]
> In the previous release, there was no such restriction. I changed the settings and everything worked fine.  I will go reflash and test as PI user.

This has been the case since the latest release. For previous versions, it had no impact.

**Comment by wpa-2** [comment]
> > In the previous release, there was no such restriction. I changed the settings and everything worked fine.  I will go reflash and test as PI user.
> 
> This has been the case since the latest release. For previous versions, it had no impact.

actually that's not the case, you could have any user but things have changed recently.

**Comment by jayofelony** [comment]
> In the previous release, there was no such restriction. I changed the settings and everything worked fine.  I will go reflash and test as PI user.

You dont need to reflash, just login as pi.

**Comment by scansonic** [comment]
> > In the previous release, there was no such restriction. I changed the settings and everything worked fine.  I will go reflash and test as PI user.
> 
> You dont need to reflash, just login as pi.

OK, I will try it.

**Comment by scansonic** [comment]
> > In the previous release, there was no such restriction. I changed the settings and everything worked fine.  I will go reflash and test as PI user.
> 
> You dont need to reflash, just login as pi.

it didn't work out for me
![Screenshot 2024-12-26-5](https://github.com/user-attachments/assets/8329b1a4-ab7b-4e18-9a1e-1777b788f965)

**Comment by wpa-2** [comment]
> > > In the previous release, there was no such restriction. I changed the settings and everything worked fine.  I will go reflash and test as PI user.
> > 
> > 
> > You dont need to reflash, just login as pi.
> 
> it didn't work out for me ![Screenshot 2024-12-26-5](https://private-user-images.githubusercontent.com/105582727/398746296-8329b1a4-ab7b-4e18-9a1e-1777b788f965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMjY2MjMsIm5iZiI6MTczNTIyNjMyMywicGF0aCI6Ii8xMDU1ODI3MjcvMzk4NzQ2Mjk2LTgzMjliMWE0LWFiN2ItNGUxOC05YTFlLTE3NzdiNzg4Zjk2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxNTE4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGVhYmM3OGVlYTM2YWIxYTEzNGZiM2Q3ZWEzYjNiZTA0ODkwZmE0OTk2ZjgyODlhNWM0NDljNzNkNGIyNDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DNfpz4xq0i9YYJ9Il1ACE9tjQ7Gs9G7_SOJ_z-Q9TXY)
> 
> I will try to reflash it.

Check debug 

sudo pwnagotchi  --debug

**Comment by scansonic** [comment]
I reflashed, and everything worked fine. So, I didn't need to enter a new user name, I just logged in as user PI.
Thank you all!

Best regards, scansonic.

**Comment by wpa-2** [comment]
> I reflashed, and everything worked fine. So, I didn't need to enter a new user name, I just logged in as user PI. Thank you all!
> 
> Best regards, scansonic.

awesome happy pwning, can you close this as sorted then please.
