### ISSUE TITLE
[Bug]: Since reflashing to 2.9.3-2 won't change from AT mode to AI mode

### ISSUE THREAD

**Issue by rsun0525** [jayofelony/pwnagotchi#283]
### Contact Details

richard.d.sun@gmail.com

### What happened?

Reflashed my pwnagotchi's to 2.9.3-2 and none of them change to AI mode
[pwnagotchi.log](https://github.com/user-attachments/files/18269879/pwnagotchi.log)

### Version

2.9.3-2

### Relevant log output

```shell
[2024-12-29 09:25:40,771] [WARNING] [MainThread] : 28 epochs with activity -> excited

so sill in AT mode
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wpa-2** [comment]
There is no AI mode any more thats been mentioned on the release notes. 
AI was removed as it was unstable, the labels will be changed in the next issue.
