### ISSUE TITLE
Add daemon.log, kern.log, syslog to rotation with pwnagotchi.log to get zipped after certain size

### ISSUE THREAD

**Issue by JD-2006** [jayofelony/pwnagotchi#29]
**Is your feature request related to a problem? Please describe.**
Most of the system logs are reaching very large sizes

**Describe the solution you'd like**
Add to main.log.path = "/var/log/pwnagotchi.log"

**Additional context**
Will this work:
main.log.path = [
  "/var/log/daemon.log",
  "/var/log/kern.log",
  "/var/log/pwnagotchi.log",
   "/var/log/syslog",
]

**Comment by IBMFFX** [comment]
Is this the reason why shutting down the pwnagotchi takes 2-5 minutes to shutdown after you've been using it a long time?  I was reading in the init.py that it does a sync of some sort.  If so can't we just truncate the logs after 30 days?
