### ISSUE TITLE
Make the dark theme a choice in the config

### ISSUE THREAD

**Issue by xslendix** [jayofelony/pwnagotchi#43]
Would be cool to have in the config something like `ui.scheme = 'dark'` or light instead of modifying the python file.

**Comment by xslendix** [comment]
I think I will work on this as I really want this

**Comment by jayofelony** [comment]
tried it, and failed. Cannot be done.

**Comment by xslendix** [comment]
> tried it, and failed. Cannot be done.

Let me try my hand at it, see if I can do smth

**Comment by jayofelony** [comment]
The display settings are loaded before anything of pwnagotchi is loaded, so you cannot make a call to config. As it will return a None type.

**Comment by jagp8** [comment]
Hmmmm crazy idea here, if you can't call the config but you can call the clock yo could make day/night mode, I mean white background from 8am to 8pm and dark background from 8pm to 8am

**Comment by jayofelony** [comment]
Yeah, but it would only change if you were to restart/reboot. As this part of the script is only used once at start of pwnagotchi.

**Comment by jagp8** [comment]
I replaced the color options with this just for fun

if int(time.strftime("%M"))%2 == 0:
    WHITE = 0x00
    BLACK = 0xFF
else:
    WHITE = 0xFF
    BLACK = 0x00

It's working as expected, it changes from color depending on the minutes being odd or even, and just to point out that it even changes when I do a pwnkill, i don't know if it should be the expected behaviour or should it only change in reboots

**Comment by Passarb** [comment]
Here is a script that I found to invert the colors.  https://github.com/tPayne0647/pwnagotchi_screen_color_invert

**Comment by jayofelony** [comment]
I am not planning on implementing any scripts.

**Comment by renewedbullet** [comment]
This should be closed the main purpose of the black background was for Jays image to stand out from others, if you want to change it you can edit view.py.

**Comment by xslendix** [comment]
I do not think this issue should be closed because of that reason, as it is a selfish reason. Not everyone likes the dark theme, adding an option for it would be good. Default could still be dark theme but the choice being there matters in my opinion.

**Comment by renewedbullet** [comment]
He has tried to add the option and it requires an astronomical amount of work to fix it correctly, plus Jay made it black to have his image be different than anyone else. You can google invert colors on Pwnagotchi and switch it back to white.

**Comment by xslendix** [comment]
I do know how to switch the colour, but I do not wish to do it every time my pwnagotchi updates. This is the whole point of the issue, figure out and plan out how this configuration option should be and work.
