### ISSUE TITLE
3.52in Waveshare display needs another rework

### ISSUE THREAD

**Issue by J4nikL** [jayofelony/pwnagotchi#64]
After building a pwnagotchi with the 3.52in display, I cam across the fact, that the face is displayed way too big. The solution would be to set the value from 100 to 50 in the font section of the waveshare3in52.py

**Comment by jayofelony** [comment]
Okay, sorry I forgot about this. It will be in v2.8.7.
![image](https://github.com/jayofelony/pwnagotchi/assets/50277312/dee3ea9f-d82e-4625-be08-15d8d96bc004)
