### ISSUE TITLE
[BUG] Waveshare V2 not working

### ISSUE THREAD

**Issue by naturekid72** [jayofelony/pwnagotchi#68]
**Describe the bug**
I cant get my Waveshare V2 Display to work. I does work with the original Version of pwnagotchi! I also connected an oledhat and that works. It is only the display that does not work.

**To Reproduce**
1. configured with "waveshare_v2" in config 
2. set to true to work
3. ...

**Expected behavior**
Show faces :-)

**Screenshots**
na, it does just not update the dislay as it normaly with other images does.

**Environment (please complete the following information):**
 - Pwnagotchi version
 - 2.8.4
 - OS version
 - Type of hardware
 - RPI0w2
 - Any additional hardware used
 - Waveshare eInk 2.13 V2

**Additional context**

**Comment by hamzenis** [comment]
I think you have to write only "waveshare_2" and not "v2"

**Comment by jayofelony** [comment]
You need set `ui.display.color = "black"` in your config.
