### ISSUE TITLE
error setting up waveshare1in54 e-paper display

### ISSUE THREAD

**Issue by bryzz42o** [jayofelony/pwnagotchi#72]
no display after installing screen and changing config,
 --debug returns

Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 235, in <module>
    pwnagotchi_cli()
  File "/usr/local/bin/pwnagotchi", line 214, in pwnagotchi_cli
    display = Display(config=config, state={'name': '%s>' % pwnagotchi.name()})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 18, in __init__
    self.init_display()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 219, in init_display
    self._implementation.initialize()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/waveshare1in54.py", line 37, in initialize
    self._display.init(0x00)
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/libs/waveshare/v1in54/epd1in54.py", line 201, in init
    for i in range(0, len(lut)):
                      ^^^^^^^^
TypeError: object of type 'int' has no len()
?????

**Comment by jayofelony** [comment]
ok let me dive into that

**Comment by bryzz42o** [comment]
appreciate you to the moon J! thought it may not be detecting the screen but "ls /dev/spi*" showed the screen occupying spi so might be in the code aka out of my league

**Comment by jayofelony** [comment]
`sudo nano /usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/waveshare1in54.py`

Can you edit this file on line 37, where it says:
`self._display.init(0x00)` into `self._display.init(0)`

Can you do that real quick for me? Than I can start a new image build with this fix.

**Comment by bryzz42o** [comment]
yep will have it done in 10 mins legend

**Comment by bryzz42o** [comment]
sorted, did you want me to submit a pull for it or just run a debug & post output?

**Comment by bryzz42o** [comment]
ui.display.type is waveshare1in54 
pwnagotchi --debug output: Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 235, in <module>
    pwnagotchi_cli()
  File "/usr/local/bin/pwnagotchi", line 214, in pwnagotchi_cli
    display = Display(config=config, state={'name': '%s>' % pwnagotchi.name()})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 18, in __init__
    self.init_display()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 219, in init_display
    self._implementation.initialize()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/waveshare1in54.py", line 37, in initialize
    self._display.init(0)
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/libs/waveshare/v1in54/epd1in54.py", line 201, in init
    for i in range(0, len(lut)):
                      ^^^^^^^^
TypeError: object of type 'int' has no len()

**Comment by bryzz42o** [comment]
Here's a possible modification to the init() method to explicitly accept lut as an argument:class EPD:
    def __init__(self):
        self.reset_pin = epdconfig.RST_PIN
        self.dc_pin = epdconfig.DC_PIN
        self.busy_pin = epdconfig.BUSY_PIN
        self.cs_pin = epdconfig.CS_PIN
        self.width = EPD_WIDTH
        self.height = EPD_HEIGHT

    lut_full_update = [
        0x02, 0x02, 0x01, 0x11, 0x12, 0x12, 0x22, 0x22,
        0x66, 0x69, 0x69, 0x59, 0x58, 0x99, 0x99, 0x88,
        0x00, 0x00, 0x00, 0x00, 0xF8, 0xB4, 0x13, 0x51,
        0x35, 0x51, 0x51, 0x19, 0x01, 0x00
    ]

    lut_partial_update = [
        0x10, 0x18, 0x18, 0x08, 0x18, 0x18, 0x08, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x13, 0x14, 0x44, 0x12,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    ]

    def init(self, lut):
        if epdconfig.module_init() != 0:
            return -1
        # EPD hardware init start
        self.reset()

        self.send_command(0x01)  # DRIVER_OUTPUT_CONTROL
        self.send_data((EPD_HEIGHT - 1) & 0xFF)
        self.send_data(((EPD_HEIGHT - 1) >> 8) & 0xFF)
        self.send_data(0x00)  # GD = 0 SM = 0 TB = 0

        self.send_command(0x0C)  # BOOSTER_SOFT_START_CONTROL
        self.send_data(0xD7)
        self.send_data(0xD6)
        self.send_data(0x9D)

        self.send_command(0x2C)  # WRITE_VCOM_REGISTER
        self.send_data(0xA8)  # VCOM 7C

        self.send_command(0x3A)  # SET_DUMMY_LINE_PERIOD
        self.send_data(0x1A)  # 4 dummy lines per gate

        self.send_command(0x3B)  # SET_GATE_TIME
        self.send_data(0x08)  # 2us per line

        self.send_command(0x11)  # DATA_ENTRY_MODE_SETTING
        self.send_data(0x03)  # X increment Y increment

        # set the look-up table register
        self.send_command(0x32)
        for i in range(0, len(lut)):
            self.send_data(lut[i])
        # EPD hardware init end
        return 0

**Comment by jayofelony** [comment]
hmm change it to a `1` and debug again :smile:

**Comment by bryzz42o** [comment]
how it looks after change --- 
def initialize(self):
        logging.info("initializing waveshare v1in54 display")
        from pwnagotchi.ui.hw.libs.waveshare.v1in54.epd1in54 import EPD
        self._display = EPD()
        self._display.init(1)
        self._display.Clear() 

"sudo pwnagotchi --debug" output:
Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 235, in <module>
    pwnagotchi_cli()
  File "/usr/local/bin/pwnagotchi", line 214, in pwnagotchi_cli
    display = Display(config=config, state={'name': '%s>' % pwnagotchi.name()})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 18, in __init__
    self.init_display()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 219, in init_display
    self._implementation.initialize()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/waveshare1in54.py", line 37, in initialize
    self._display.init(1)
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/libs/waveshare/v1in54/epd1in54.py", line 201, in init
    for i in range(0, len(lut)):
                      ^^^^^^^^
TypeError: object of type 'int' has no len()

here's my config for clarity:
main.name = "blipppy"
main.lang = "en"
main.whitelist = [
 "hedgewitch",
 "ANOTHER_EXAMPLE_NETWORK",
 "fo:od:ba:be:fo:od",
 "fo:od:ba",
]
main.confd = "/etc/pwnagotchi/conf.d/"
main.custom_plugin_repos = [
 "https://github.com/jayofelony/pwnagotchi-torch-plugins/archive/master.zip",
 "https://github.com/tisboyo/pwnagotchi-pisugar2-plugin/archive/master.zip",
 "https://github.com/nullm0ose/pwnagotchi-plugin-pisugar3/archive/master.zip",
 "https://github.com/Sniffleupagus/pwnagotchi_plugins/archive/master.zip",
 "https://github.com/NeonLightning/pwny/archive/master.zip",
 "https://github.com/marbasec/UPSLite_Plugin_1_3/archive/master.zip",
 "https://github.com/Kaska89/pwnagotchi-EXPv2-plugin/archive/master.zip",
]
main.custom_plugins = "/usr/local/share/pwnagotchi/custom-plugins/"
main.plugins.aircrackonly.enabled = true
main.plugins.aircrackonly.face = "(>.<)"

main.plugins.hashie.enabled = true

main.plugins.auto-update.enabled = true
main.plugins.auto-update.install = true
main.plugins.auto-update.interval = 1

main.plugins.bt-tether.enabled = true
main.plugins.bt-tether.devices.android-phone.enabled = false
main.plugins.bt-tether.devices.android-phone.search_order = 1
main.plugins.bt-tether.devices.android-phone.mac = ""
main.plugins.bt-tether.devices.android-phone.ip = "192.168.44.44"
main.plugins.bt-tether.devices.android-phone.netmask = 24
main.plugins.bt-tether.devices.android-phone.interval = 1
main.plugins.bt-tether.devices.android-phone.scantime = 10
main.plugins.bt-tether.devices.android-phone.max_tries = 10
main.plugins.bt-tether.devices.android-phone.share_internet = false
main.plugins.bt-tether.devices.android-phone.priority = 1

main.plugins.bt-tether.devices.ios-phone.enabled = false
main.plugins.bt-tether.devices.ios-phone.search_order = 2
main.plugins.bt-tether.devices.ios-phone.mac = ""
main.plugins.bt-tether.devices.ios-phone.ip = "172.20.10.6"
main.plugins.bt-tether.devices.ios-phone.netmask = 24
main.plugins.bt-tether.devices.ios-phone.interval = 5
main.plugins.bt-tether.devices.ios-phone.scantime = 20
main.plugins.bt-tether.devices.ios-phone.max_tries = 0
main.plugins.bt-tether.devices.ios-phone.share_internet = false
main.plugins.bt-tether.devices.ios-phone.priority = 999
main.plugins.fix_services.enabled = true

main.plugins.gdrivesync.enabled = false
main.plugins.gdrivesync.backupfiles = [ "",]
main.plugins.gdrivesync.backup_folder = "PwnagotchiBackups"

main.plugins.gpio_buttons.enabled = false

main.plugins.gps.enabled = false
main.plugins.gps.speed = 19200
main.plugins.gps.device = "/dev/ttyUSB0"

main.plugins.grid.enabled = true
main.plugins.grid.report = true

main.plugins.logtail.enabled = false
main.plugins.logtail.max-lines = 10000

main.plugins.memtemp.enabled = true
main.plugins.memtemp.scale = "celsius"
main.plugins.memtemp.orientation = "horizontal"

main.plugins.net-pos.enabled = false
main.plugins.net-pos.api_key = "test"

main.plugins.onlinehashcrack.enabled = false
main.plugins.onlinehashcrack.email = ""
main.plugins.onlinehashcrack.dashboard = ""
main.plugins.onlinehashcrack.single_files = false

main.plugins.pisugar2.enabled = false
main.plugins.pisugar2.shutdown = 5
main.plugins.pisugar2.sync_rtc_on_boot = false

main.plugins.session-stats.enabled = true
main.plugins.session-stats.save_directory = "/var/tmp/pwnagotchi/sessions/"

main.plugins.ups_hat_c.enabled = false
main.plugins.ups_hat_c.label_on = true
main.plugins.ups_hat_c.shutdown = 5
main.plugins.ups_hat_c.bat_x_coord = 140
main.plugins.ups_hat_c.bat_y_coord = 0

main.plugins.ups_lite.enabled = false
main.plugins.ups_lite.shutdown = 2

main.plugins.webcfg.enabled = true

main.plugins.webgpsmap.enabled = false
main.plugins.wigle.enabled = false
main.plugins.wigle.api_key = ""
main.plugins.wigle.donate = false

main.plugins.wpa-sec.enabled = true
main.plugins.wpa-sec.api_key = "2c86172d12cf749250a766d1bc612717"
main.plugins.wpa-sec.api_url = "https://wpa-sec.stanev.org"
main.plugins.wpa-sec.download_results = true

main.plugins.expv2.enabled = true
main.plugins.expv2.lvl_x_coord = 0
main.plugins.expv2.lvl_y_coord = 81
main.plugins.expv2.exp_x_coord = 38
main.plugins.expv2.exp_y_coord = 81
main.plugins.expv2.str_x_coord = 80
main.plugins.expv2.str_y_coord = 32
main.plugins.expv2.bar_symbols_count = 12

main.plugins.agev2.enabled = true
main.plugins.agev2.age_x_coord = 0
main.plugins.agev2.age_y_coord = 32

main.plugins.internet-connection.enabled = true

main.plugins.IPDisplay.enabled = true
main.plugins.IPDisplay.skip_devices = [ "lo",]

main.plugins.tweak_view.enabled = true

main.plugins.Touch_UI.enabled = false

main.plugin.gdrivesync.interval = 1

main.iface = "wlan0mon"
main.mon_start_cmd = "/usr/bin/monstart"
main.mon_stop_cmd = "/usr/bin/monstop"
main.mon_max_blind_epochs = 50
main.no_restart = false
main.filter = ""
main.log.path = "/home/pi/logs/pwnagotchi.log"
main.log.rotation.enabled = true
main.log.rotation.size = "10M"

ai.enabled = true
ai.path = "/root/brain.nn"
ai.laziness = 0.1
ai.epochs_per_episode = 50
ai.params.gamma = 0.99
ai.params.n_steps = 1
ai.params.vf_coef = 0.25
ai.params.ent_coef = 0.01
ai.params.max_grad_norm = 0.5
ai.params.learning_rate = 0.001
ai.params.verbose = 1

personality.advertise = true
personality.deauth = true
personality.associate = true
personality.channels = [
 5,
 6,
 7,
 8,
 9,
 11,
 36,
 64,
 100,
 108,
 116,
 120,
 124,
 132,
 136,
 144,
 161,
]
personality.min_rssi = -192
personality.ap_ttl = 278
personality.sta_ttl = 259
personality.recon_time = 60
personality.max_inactive_scale = 5
personality.recon_inactive_multiplier = 2
personality.hop_recon_time = 16
personality.min_recon_time = 22
personality.max_interactions = 25
personality.max_misses_for_recon = 6
personality.excited_num_epochs = 8
personality.bored_num_epochs = 26
personality.sad_num_epochs = 11
personality.bond_encounters_factor = 20000
personality.throttle_a = 0.4
personality.throttle_d = 0.9
personality.clear_on_exit = true

ui.fps = 1
ui.font.name = "DejaVuSansMono"
ui.font.size_offset = 0

ui.faces.look_r = "( ⚆_⚆)"
ui.faces.look_l = "(☉_☉ )"
ui.faces.look_r_happy = "( ◕‿◕)"
ui.faces.look_l_happy = "(◕‿◕ )"
ui.faces.sleep = "(⇀‿‿↼)"
ui.faces.sleep2 = "(≖‿‿≖)"
ui.faces.awake = "(◕‿‿◕)"
ui.faces.bored = "(-__-)"
ui.faces.intense = "(°▃▃°)"
ui.faces.cool = "(⌐■_■)"
ui.faces.happy = "(•‿‿•)"
ui.faces.excited = "(ᵔ◡◡ᵔ)"
ui.faces.grateful = "(^‿‿^)"
ui.faces.motivated = "(☼‿‿☼)"
ui.faces.demotivated = "(≖__≖)"
ui.faces.smart = "(✜‿‿✜)"
ui.faces.angry = "(-_-')"
ui.faces.friend = "(♥‿‿♥)"
ui.faces.broken = "(☓‿‿☓)"
ui.faces.debug = "(#__#)"
ui.faces.upload = "(1__0)"
ui.faces.upload1 = "(1__1)"
ui.faces.upload2 = "(0__1)"

ui.web.enabled = true
ui.web.address = "0.0.0.0"
ui.web.username = "pwno"
ui.web.password = "craigsmomsbush"
ui.web.origin = ""
ui.web.port = 8080
ui.web.on_frame = ""

ui.display.enabled = true
ui.display.rotation = 180
ui.display.type = "waveshare1in54"
ui.display.color = "black"

bettercap.handshakes = "/root/handshakes"
bettercap.silence = [
 "ble.device.new",
 "ble.device.lost",
 "ble.device.disconnected",
 "ble.device.connected",
 "ble.device.service.discovered",
 "ble.device.characteristic.discovered",
 "wifi.client.new",
 "wifi.client.lost",
 "wifi.client.probe",
 "wifi.ap.new",
 "wifi.ap.lost",
 "mod.started",
]

fs.memory.enabled = true
fs.memory.mounts.log.enabled = true
fs.memory.mounts.log.mount = "/home/pi/logs"
fs.memory.mounts.log.size = "50M"
fs.memory.mounts.log.sync = 60
fs.memory.mounts.log.zram = true
fs.memory.mounts.log.rsync = true

fs.memory.mounts.data.enabled = true
fs.memory.mounts.data.mount = "/var/tmp/pwnagotchi"
fs.memory.mounts.data.size = "10M"
fs.memory.mounts.data.sync = 3600
fs.memory.mounts.data.zram = true
fs.memory.mounts.data.rsync = true

**Comment by jayofelony** [comment]
Can you set it as this?
`self._display.init(self._display.lut_full_update)`

**Comment by bryzz42o** [comment]
That fixed the len error, unfortunately screen still not displaying so I'll recheck all the pin connections today. Could possibly be the tweak_view changing the disp settings or something so will turn off all the plugins later and see if running bare bones helps it display the screen

**Comment by bryzz42o** [comment]
No luck running bare bones and reseating the pins, If the repo supports piTfT screens I'll try one I have later to confirm this e-paper isn't faulty but is only a couple days old so unlikely. Appreciate all the help

**Comment by jayofelony** [comment]
If you have a v2 b version you need to use different display type

**Comment by bryzz42o** [comment]
changed & --debug: unsupported display type waveshare1in54b_v2

**Comment by bryzz42o** [comment]
changed & success with waveshare1in54b <3 incase anyone else ends up here its the 1.54inch e-paper waveshare screen with a GREEN sticker on the front protector film
