### ISSUE TITLE
[BUG] Update fails

### ISSUE THREAD

**Issue by simphide** [jayofelony/pwnagotchi#76]
**Describe the bug**
I run the command sudo pwnagotchi --check-update and nothing happens
![image](https://github.com/jayofelony/pwnagotchi/assets/8183517/dbcc4553-7bcd-44a5-ae4f-33d543f89b71)

**To Reproduce**
1.  sudo pwnagotchi --check-update
2. pwnlog

**Expected behavior**
Pwnagotchi gets updated

**Screenshots**
![image](https://github.com/jayofelony/pwnagotchi/assets/8183517/874ede52-7a5e-4f19-9422-ed6cbaf8ffee)

<img width="1375" alt="image" src="https://github.com/jayofelony/pwnagotchi/assets/8183517/3a9d1575-3e52-4f5f-bb69-ca7a7f58037f">

**Environment (please complete the following information):**
 - Pwnagotchi 2.8.2
 - Pi Zero 2 W
 - nothing

**Additional context**
I don't know what should happen...

**Comment by jayofelony** [comment]
You have to reflash sadly

**Comment by jayofelony** [comment]
This one specifically because of repo name change. Otherwise I will tell in release notes if I recommend it.

**Comment by simphide** [comment]
the update was successful! Just a quick question @jayofelony - what is the new text in the bottom right cornor? "rst#1"

**Comment by jayofelony** [comment]
Thats the counter how many times the wifi firmware is being reset. It will be removed in the next update.
