### ISSUE TITLE
[2.8.6 Issue fix here] Pwnagotchi doesnt start because "Cannot concatenate bool() to str()" temp fix here

### ISSUE THREAD

**Issue by rai68** [jayofelony/pwnagotchi#79]
Issue created by #77 
fixed in #78 

Below is a temporary fix for 2.8.6 users.

64bit `sudo rm /usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/view.py && sudo wget --directory-prefix=/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/ https://raw.githubusercontent.com/rai68/pwnagotchi/master/pwnagotchi/ui/view.py`

32bit `sudo rm /usr/local/lib/python3.9/dist-packages/pwnagotchi/ui/view.py && sudo wget --directory-prefix=/usr/local/lib/python3.9/dist-packages/pwnagotchi/ui/ https://raw.githubusercontent.com/rai68/pwnagotchi/master/pwnagotchi/ui/view.py`

**Comment by jayofelony** [comment]
2.8.6 is in pre-release, so I will remove it and build a new image.
