### ISSUE TITLE
Pwnagotchi not getting updated

### ISSUE THREAD

**Issue by jagp8** [jayofelony/pwnagotchi#80]
So I try to do an pwnagotchi --check-update and it finds it and seems to try to apply  it, it even restarts the pwnagotchi service, but it's  not getting updated

```
Kite@Asuranceturix:~ $ date
Wed  6 Mar 00:21:43 CET 2024
Kite@Asuranceturix:~ $ sudo pwnagotchi --check-update
There is a new version available! Update from v2.8.4 to v2.8.6?
[y(es)/n(o)]y
Okay, give me a couple minutes. Just watch pwnlog while you wait.
Kite@Asuranceturix:~ $ date
Wed  6 Mar 00:36:41 CET 2024
Kite@Asuranceturix:~ $ pwnagotchi --version
2.8.4
```
I've tried several times even left it like that for an hour buth nohing
The rest it's working without problems, is there any other way to try to force the update? Some other command or cal to a script?
Thanks in advance!

**Comment by jayofelony** [comment]
You need to reflash,there have been several big changes that interfere with auto-update.
