### ISSUE TITLE
[HELP] WaveshareV4 not drawing on PI 02W (Device Busy)

### ISSUE THREAD

**Issue by aalejandrofer** [jayofelony/pwnagotchi#81]
**Hardware**
- Pi Zero 2 W
- Waveshare 2.13inch e-Paper HAT v4

**Describe the bug**
When launching Pwnagotchi the web interface is up and running but the waveshare screen does not draw any images. 
- I have tested the screen on a pi4b and the image draws, I have texted the waveshare team but no reply wanted to see if anyone here encountered the same problem. 
- [Not Tested] I have heard that it has something to do with the screen being connected using the headers instead of wired. I want to avoid wiring it.

**Config**
ui.display.enabled = true
ui.display.type = "waveshare_4"
ui.display.color = “black”

**More Info**
```
ls /dev/spi* 
> /dev/spidev0.0  /dev/spidev0.1  /dev/spidev1.0  /dev/spidev1.1  /dev/spidev1.2

sudo pwnagotchi --debug
....
> AttributeError: 'Display' object has no attribute 'is_waveshare27inch'
[2024-01-26 23:19:32,646] [INFO] initializing waveshare v2in13_V4 display
INFO:root:BT-TETHER: Successfully loaded ...
[2024-01-26 23:19:32,673] [INFO] BT-TETHER: Successfully loaded ...
DEBUG:pwnagotchi.ui.hw.libs.waveshare.v2in13_V4.epd2in13_V4:e-Paper busy
[2024-01-26 23:19:32,715] [DEBUG] e-Paper busy
```

I have tested with waveshare_3 but same

**Comment by jayofelony** [comment]
disable gps plugin
