### ISSUE TITLE
[BUG] display not updating

### ISSUE THREAD

**Issue by benallard** [jayofelony/pwnagotchi#99]
I flashed an old raspi-zero (32-bits) with the latest Pwnagotchi image.

the display is not being updated at all (not even at boot).

I'm pretty sure it should be working as the previous image was displaying stuff.

The log is properly displaying the initialisation, but nothing more:

```
initializing waveshare v2in13_V2 display
```

(I have a waveshare_2 display).

**Comment by benallard** [comment]
The image seems to have some issues (See #98), so ,it could be related.

**Comment by jayofelony** [comment]
Are you in AUTO/AI mode or in MANU mode?

**Comment by jayofelony** [comment]
im on it

**Comment by benallard** [comment]
Oh, great, let me know if I need to test something.
